### PR TITLE
UE5 Support

### PR DESCRIPTION
**Pull request by brwarner**
Adding UE5 support through the new ToolsMenu API along with appropriate updates to the Readme.

### CODE REVIEW

**Comment by brwarner** [comment]
Builds and runs on both UE4.26 and UE5 Early Access 2.

**Comment by jahxsis** [comment]
When I import to Unreal 5, I only get about 30 **.h** files in"C++ Classes>Articy Generated," No Blueprints, objects, or anything else to interact with.  Is it supposed to be making more files than that, or am I doing something wrong?

**Comment by brwarner** [comment]
> When I import to Unreal 5, I only get about 30 **.h** files in"C++ Classes>Articy Generated," No Blueprints, objects, or anything else to interact with. Is it supposed to be making more files than that, or am I doing something wrong?

Hey @jahxsis,

You should be getting objects stored in database and package assets created under Content/ArticyGenerated as usual. Are you getting any errors or warnings in your Output window in Unreal? Anything that might provide a hint about what's going wrong? Also, what happens if you try to trigger a Full Reimport via the button under the Settings menu on the far right of the level editor screen (see the image in the Readme).

If the problem persists, can you create a new Issue in Github? It'll be easier to track instead of replying to this closed pull request.

**Comment by jahxsis** [comment]
Hi Brook, thanks for your quick attention!

A full re-import does not change anything. Have tried many new imports,
reimports, and regenerating assets.

I do see a folder and two files in the  Content/ArticyGenerated folder, but
that is all. Am I supposed to do something with those files?

Joel

**Comment by brwarner** [comment]
Hey Joel,

Have you used Articy for Unreal before? Or is this the first time you're trying it on any version?

The Articy for Unreal importer doesn't really create any Blueprints or working game objects for you. What it does is create C++ classes, structs, and enums to mirror the data in your Articy project, then creates instances of those objects for each entity, flow node, etc. and stores them in package objects like the one you're seeing in Content/ArticyGenerated.

To ensure it's working correctly, create a Articy Flow Debugger object from the Create menu and place it on your level.

image

You should then be able to edit its "Start On" property.

image

When you click the "None" drop-down, you should see a list of all the flow nodes in your imported Articy project.

Screen Shot 08-29-21 at 10 05 AM

If you see that, then the import was successful. You can now start building your own blueprints/code to do something with all the data you importer from Articy. I suggest following the [tutorial on our Readme starting from Using the API](https://github.com/ArticySoftware/ArticyImporterForUnreal#using-the-api) to build a simple UI interface that lets the player navigate a simple branching conversation.

**Comment by jahxsis** [comment]
Thank you for this detailed explanation. I had used it briefly with UE4,
but hadn't gotten this far.

I will work through this step by step process and imagine I will have more
success now!

Thanks again,

Joel

**Comment by jahxsis** [comment]
Brook,

All right, I am getting somewhere now. It looks like it is working as it is
supposed to, and the problem was my lack of knowledge.

Can you link me to the appropriate tutorial that shows how to use Articy
objects in Unreal. I swear I have been trying to track it down but haven't
found it yet.

Thanks,

Joel

**Comment by brwarner** [comment]
Hey, 

Here's the link again: https://github.com/ArticySoftware/ArticyImporterForUnreal#using-the-api

You'll need some existing familiarity with Unreal and Blueprint.

If you have more questions, can you ask them as  new issue in Github here: https://github.com/ArticySoftware/ArticyImporterForUnreal/issues . This is a closed pull request so it doesn't appear as a notification anywhere when you reply to it.

**Pull request merged**
